// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ZkG8T5bzBIikXMGOQMLDXfUFkUcV13Q',
    appId: '1:36065343136:web:dd655b8effd9e41fe53bc5',
    messagingSenderId: '36065343136',
    projectId: 'parking-project-fb2ef',
    authDomain: 'parking-project-fb2ef.firebaseapp.com',
    storageBucket: 'parking-project-fb2ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAClM_fF7k4A7rldLs_53VjG9dvZQ5roXc',
    appId: '1:36065343136:android:740ed87867e43064e53bc5',
    messagingSenderId: '36065343136',
    projectId: 'parking-project-fb2ef',
    storageBucket: 'parking-project-fb2ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPFGVA_JF7sd8yvuRI6jnOURBlnCQlB1Q',
    appId: '1:36065343136:ios:fe6a310f61064511e53bc5',
    messagingSenderId: '36065343136',
    projectId: 'parking-project-fb2ef',
    storageBucket: 'parking-project-fb2ef.appspot.com',
    iosClientId:
        '36065343136-molarubb28veiiv8ll1imni2q5enkqbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkingImage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPFGVA_JF7sd8yvuRI6jnOURBlnCQlB1Q',
    appId: '1:36065343136:ios:fe6a310f61064511e53bc5',
    messagingSenderId: '36065343136',
    projectId: 'parking-project-fb2ef',
    storageBucket: 'parking-project-fb2ef.appspot.com',
    iosClientId:
        '36065343136-molarubb28veiiv8ll1imni2q5enkqbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkingImage',
  );
}
